- Store Performance

Step 1 : Import Required Libraries

In [1]:
import numpy as np
import pandas as pd

Step 2 : Import Dataset & Backup

In [2]:
Stores=pd.read_csv(r"C:\Users\Lap Tech\Desktop\Stores\Stores.csv")

Stoers_Backup=Stores.copy()

Step 3 : EDA ( Explory Data Analysis )

In [3]:
Stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Store ID              896 non-null    int64
 1   Store_Area            896 non-null    int64
 2   Items_Available       896 non-null    int64
 3   Daily_Customer_Count  896 non-null    int64
 4   Store_Sales           896 non-null    int64
dtypes: int64(5)
memory usage: 35.1 KB

In [5]:
Stores.head(10)

   Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
0          1        1659             1961                   530        66490
1          2        1461             1752                   210        39820
2          3        1340             1609                   720        54010
3          4        1451             1748                   620        53730
4          5        1770             2111                   450        46620
5          6        1442             1733                   760        45260
6          7        1542             1858                  1030        72240
7          8        1261             1507                  1020        37720
8          9        1090             1321                   680        46310
9         10        1030             1235                  1130        44150

In [6]:
Stores.tail(10)

     Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
886        887        1655             1986                  1150        77430
887        888        1156             1398                   140        92370
888        889        1451             1734                   670        34880
889        890        1539             1829                   650        46580
890        891        1549             1851                  1220        70620
891        892        1582             1910                  1080        66390
892        893        1387             1663                   850        82080
893        894        1200             1436                  1060        76440
894        895        1299             1560                   770        96610
895        896        1174             1429                  1110        54340

In [7]:
Stores.sample(10)

     Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
5            6        1442             1733                   760        45260
567        568        2026             2400                   720        51240
398        399        2063             2493                   810        51480
615        616        1426             1718                   370        47570
883        884        1357             1625                  1140        52160
753        754        1453             1749                   890        58440
273        274        1617             1901                   490        60770
762        763        1197             1428                   830        65410
765        766        1562             1881                   740        54530
253        254        1428             1719                  1060        39800

In [8]:
Stores.describe()

,Store ID,Store_Area,Items_Available,Daily_Customer_Count,Store_Sales
count,896.000000,896.000000,896.000000,896.000000,896.000000
mean,448.500000,1485.409598,1782.035714,786.350446,59351.305804
std,258.797218,250.237011,299.872053,265.389281,17190.741895
min,1.000000,775.000000,932.000000,10.000000,14920.000000
25%,224.750000,1316.750000,1575.500000,600.000000,46530.000000
50%,448.500000,1477.000000,1773.500000,780.000000,58605.000000
75%,672.250000,1653.500000,1982.750000,970.000000,71872.500000
max,896.000000,2229.000000,2667.000000,1560.000000,116320.000000

In [19]:
print('Total Duplicats Vallues :', Stores.duplicated().sum())
print('Null Vallues Per Column :\n' ,Stores.isnull().sum())

Total Duplicats Vallues : 0
Null Vallues Per Column :
 Store ID                0
Store_Area              0
Items_Available         0
Daily_Customer_Count    0
Store_Sales             0
dtype: int64